# test_alert.py
import requests
import json

# Generate test alert
alert = {
    "title": "Test Security Alert",
    "severity": "high",
    "description": "Test alert generated by setup",
    "source": "test",
    "timestamp": "2024-01-01T00:00:00Z",
    "indicators": ["192.168.1.1"],
    "type": "test"
}

# Send to platform
response = requests.post(
    "http://localhost:8000/api/alerts",
    headers={"X-API-Key": "your_api_key"},
    json=alert
)

print(f"Alert sent: {response.status_code}")